package com.certuit.base.domain.request.base;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PlantillaRequest {
    int idPlantilla = 0;
    String archivoBase64 = "";
    String archivoNombre = "";
    String hojaEmbarques = "";
    String hojaPaquetes = "";
    String hojaComplementos = "";
    String numeroEmbarque = "";
    String esRecoleccion = "";
    String moneda = "";
    String tipoCambio = "";
    String tipoCobro = "";
    int idCliente = 0;
    String tipoSeguro = "";
    String porcentajeSeguro = "";
    String valorDeclarado = "";
    String observacionesEmbarque = "";
    String validarTimbradoFactura = "";
    String tipoServicio = "";
    String numeroRemitente = "";
    String correoRemitente = "";
    String telefonoRemitente = "";
    String contactoRemitente = "";
    String numeroDestinatario = "";
    String correoDestinatario = "";
    String telefonoDestinatario = "";
    String contactoDestinatario = "";
    String entregaEnSucursal = "";
    String sucursalEntrega = "";
    String entregaDiferenteDomicilio = "";
    String codigoPostalDiferenteDomicilio = "";
    String coloniaDiferenteDomicilio = "";
    String calleNumeroDiferenteDomicilio = "";
    String entregarEn = "";
    String datosAdicionales = "";
    String recoleccionDiferenteDomicilio = "";
    String codigoPostalDiferenteDomicilioRecoleccion = "";
    String coloniaDiferenteDomicilioRecoleccion = "";
    String calleNumeroDiferenteDomicilioRecoleccion = "";
    String recogerEn = "";
    String datosAdicionalesRecoleccion = "";
    String latitud = "";
    String longitud = "";
    String conCita = "";
    String citaPendiente = "";
    String fechaCita = "";
    String horaMinimaCita = "";
    String horaMaximaCita = "";
    String cantidadPaquete = "";
    String numeroProducto = "";
    String embalajePaquete = "";
    String largo = "";
    String alto = "";
    String ancho = "";
    String pesoPaquete = "";
    String observacionesPaquete = "";
    String descripcionPaquete = "";
    String cantidadComplemento = "";
    String pesoComplemento = "";
    String claveProductoServicio = "";
    String claveUnidadMedida = "";
    String esMaterialPeligroso = "";
    String claveMaterialPeligroso = "";
    String claveEmbalaje = "";
    String descripcionEmbalajeComplemento = "";
    String claveFraccionArancelaria = "";
    int idTipoPlantilla = 0;
    boolean usarNumeroEquivalenciaRemitente = false;
    boolean usarNumeroEquivalenciaDestinatario = false;
    boolean usarNumeroEquivalenciaResponsablePago = false;
    String responsablePago = "";
    String referencia = "";
    String esFarmaco="";
    String claveSectorCofepris="";
    String nombreIngredienteActivo="";
    String nombreQuimico="";
    String denominacionGenericaProd="";
    String denominacionDistintivaProd="";
    String fabricante="";
    String fechaCaducidad="";
    String loteMedicamento="";
    String formaFarmaceutica="";
    String condicionesEspTransp="";
    String registroSanitarioFolioAutorizacion="";
    String numeroCAS="";
    String numRegSanPlagCOFEPRIS="";
    String datosFabricante="";
    String datosFormulador="";
    String datosMaquilador="";
    String usoAutorizado="";
}
